
// This file was generated by a tool. 
// Changes to this file may cause incorrect behavior and will be lost if the file is regenerated. 

"use strict";

var ValuedPartnerSampleARInvoiceEntryCustomizationUI = ValuedPartnerSampleARInvoiceEntryCustomizationUI || {};
var ValuedPartnerSampleARInvoiceEntrycustomizationViewModel;

ValuedPartnerSampleARInvoiceEntryCustomizationUI = {

    // Init
    init: function () {
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initIntercept();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initAjaxCallIntercept();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initButtons();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initFinders();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initTextbox();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initNumericTextBox();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initDropDownList();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initDatePicker();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initCheckBoxes();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initGrid();
        ValuedPartnerSampleARInvoiceEntryCustomizationUI.initOtherControls();
		
		// Issuing a dummy call to get the Payment Code view model
		// in order to populate the dropdown of payment codes
		// Assign url (module, controller, action) to get
		var url = sg.utls.url.buildUrl("AR", "PaymentCode", "Get");
		// Assign model for parameter(s) of Get action
		var model = { id: "CASH" };
		sg.utls.ajaxPost(url, model, ValuedPartnerSampleARInvoiceEntryCustomizationUICallback.populateDropdown);
		// Refresh the grid
		ValuedPartnerSampleARInvoiceEntryCustomizationUI.refreshGrid();
		
    },

    //Hijack and intercept events, before the event
    initIntercept: function () {
    },

    //Intercept before/after Ajax calls
    initAjaxCallIntercept: function () {

        $(document).ajaxSend(function (event, jqxhr, settings) {
        });

        $(document).ajaxSuccess(function (event, xhr, settings) {
        });

    },

    // Init Buttons
    initButtons: function () {
		// This is an example of adding some space after the newly added Delete button
		$("#vpPaymentCodeDeleteButton").css('margin-right', 20);
		// Initialize the Delete button's click event
		$("#vpPaymentCodeDeleteButton").on('click', function (e) {
			// Get value from Payment Code textbox
			var value = $("#vpPaymentCodeTextbox").val();
			// If a value is in the textbox, issue a call to the delete method
			if (value) {
			   // Assign url (module, controller, action) to delete
			   var url = sg.utls.url.buildUrl("AR", "PaymentCode", "Delete");
			   // Assign model for parameter(s) of Delete action
			   var model = { id: value };
			   // Post delete and specify call back
			   sg.utls.ajaxPost(url, model, ValuedPartnerSampleARInvoiceEntryCustomizationUICallback.delete);
			}
		});
		// Initialize the Save button's click event
		$("#vpPaymentCodeSaveButton").on('click', function (e) {
		   // Get value fom Payment Code textbox
		   var value = $("#vpPaymentCodeTextbox").val();
		   if (!value) {
			  return;
		   }
		   // Locate the payment code grid
		   var grid = $("#vpPaymentCodeGrid").data("kendoGrid");
		   // Get list of payment codes in grid
		   var list = grid.dataSource.data();
		   // Filter the list based upon value in present in the textbox
		   var filteredList = list.filter(function (item) { return item.PaymentCode == value; });
		   // Determine if the Save will perform an add or update
		   if (filteredList.length == 0) {
			  // Not in list and therefore a new code
			  ValuedPartnerSampleARInvoiceEntryCustomizationUI.add();
		   } else {
			  // For update, we will get record first for concurrency check (ETag)
			  // Assign url (module, controller, action) to get
			  var url = sg.utls.url.buildUrl("AR", "PaymentCode", "Get");
			  // Assign model for parameter(s) of Get action
			  var model = { id: value };
			  // Post get and specify call back
			  sg.utls.ajaxPost(url, model, ValuedPartnerSampleARInvoiceEntryCustomizationUICallback.update);
		   }
		});
		
    },

    // Init TextBoxs
    initTextbox: function(){
		// This is an example of changing the styling on the textbox
		$("#vpPaymentCodeTextbox").removeClass("smaller").addClass("default");
		// This is an example of starting a new line
		$("<br/>").insertBefore($("#vpModifiedDatePicker").parent());
    },

    // Init Numeric TextBox
    initNumericTextBox: function () {
    },

    // Init Dropdown List
    initDropDownList: function () {
		// Initialize the dropdown list
		$("#vpPaymentCodeTypeDropdown").kendoDropDownList({
		   dataTextField: "Text",
		   dataValueField: "Value",
		   change: function (e) {
			  var idx = this.selectedIndex;
			  $("#vpPaymentCodeTypeDropdown").val(this.value());
		   }
		});
    },

    // Init Date Picker
    initDatePicker: function() {
		// Initialize the date picker
		$("#vpModifiedDatePicker").kendoDatePicker({});
		$('#vpModifiedDatePicker').data("kendoDatePicker").value(new Date());
    },

    // Init Sage 300 Finders
    initFinders: function () {
		
		// Init the finder
		sg.viewFinderHelper.setViewFinderEx("vpPaymentCodeFinder", "vpPaymentCodeTextbox", sg.viewFinderProperties.AR.PaymentCodes, ValuedPartnerSampleARInvoiceEntryCustomizationUICallback.finderSuccess, null);
    },

    //Init CheckBoxs
    initCheckBoxes: function () {
    },

    //Init kendo Grid
    initGrid: function () {
		// Initialize the grid
		$("#vpPaymentCodeGrid").kendoGrid({
		   dataSource: [],
		   height: 300,
		   resizable: true,
		   selectable: true,
		   reorderable: true,
		   editable: false,
		   change: onSelectChange,
		   columns: [
			  {
				 field: "PaymentCode",
				 title: "Payment Code",
				 width: "100px"
			  },
			  {
				 field: "Description",
				 title: "Description",
				 width: "160px"
			  },
			  {
				 field: "PaymentTypeString",
				 title: "Payment Type",
				 width: "120px"
			  },
			  {
				 field: "StatusString",
				 title: "Status",
				 width: "120px"
			  },
		   ]
		});

		// Establish the OnSelectChange function
		function onSelectChange(e) {
		   // Get the grid control
		   var grid = $("#vpPaymentCodeGrid").data("kendoGrid");
		   // Get the selected row
		   var row = grid.dataItem(grid.select());
		   // If a row was selected, push values into controls since this is not data bound
		   if (row) {
			  $("#vpPaymentCodeTextbox").val(row.PaymentCode);
			  $("#vpPaymentCodeDescTextbox").val(row.Description);
		      $('#vpPaymentCodeTypeDropdown').data("kendoDropDownList").text(row.PaymentTypeString);
		   }
		}
    },

    //Init Other type controls
    initOtherControls: function () {
    },

	// Refresh the grid utilizing the finder's RefreshGrid method
	refreshGrid: function () {
	   // Assign url (module, controller, action)
	   var url = sg.utls.url.buildUrl("Core", "Find", "RefreshGrid");
	   // Assign the parameters
	   //var postData = { finderOptions: { AdvancedFilter: null, PageNumber: 0, PageSize: 30, SearchFinder: sg.finder.PaymentCode, SimpleFilter: null } };
	   var postData = { finderOptions: { AdvancedFilter: null, PageNumber: 0, PageSize: 30, SearchFinder: sg.viewFinderProperties.AR.PaymentCodes, SimpleFilter: null } };
	   sg.utls.ajaxPost(url, postData,  ValuedPartnerSampleARInvoiceEntryCustomizationUICallback.setGridDataSource); 
	},
	
	// Add a new code that does not exist in the grid
	add: function() {
	   // Assign url (module, controller, action)
	   var url = sg.utls.url.buildUrl("AR", "PaymentCode", "Add");
	   // Assign the parameters
	   var model = {
		  DateLastMaintained: new Date(),
		  Description: $("#vpPaymentCodeDescTextbox").val(),
		  DisplayIndex: 0,
		  InactiveDate: new Date(1970, 1, 1),
		  PaymentCode: $("#vpPaymentCodeTextbox").val(),
		  PaymentType: $('#vpPaymentCodeTypeDropdown').data("kendoDropDownList").value(),
		  Status: 1
	   }
	   // Post and specify call back
	   sg.utls.ajaxPost(url, model, ValuedPartnerSampleARInvoiceEntryCustomizationUICallback.save);
	},
};


var ValuedPartnerSampleARInvoiceEntryCustomizationUICallback = {
	// Populate fields based on finder selection, if any
	finderSuccess: function (data) {
		// Data is not null if a value is selected in the finder
		if (data) {
			// Populate controls
			$("#vpPaymentCodeTextbox").val(data.PAYMCODE);
			$("#vpPaymentCodeDescTextbox").val(data.TEXTDESC);
			$('#vpPaymentCodeTypeDropdown').data("kendoDropDownList").value(data.PAYMTYPE);
			// Set focus to textbox
			sg.controls.Focus($("#vpPaymentCodeTextbox"));
		}
	},
	
	// Populate the dropdown list from view model
	populateDropdown: function (viewModel) {
	   // GetPaymentType of view model is a dynamic list
	   var list = viewModel.GetPaymentType;
	   // Get dropdown control
	   var dropdown = $("#vpPaymentCodeTypeDropdown").data("kendoDropDownList");
	   // Set list to the datasource of dropdown
	   dropdown.setDataSource(list);
	   // Select the first item
	   dropdown.select(0);
	},
	
	// Callback from refreshGrid routine
	setGridDataSource: function (data) {

		if (data) {
			// Get grid control
			var grid = $("#vpPaymentCodeGrid").data("kendoGrid");
			// Assign to datasource of grid
			grid.dataSource.data(data.Data);
		}
	},
	
	// Callback from the add routine
	save: function (data) {
	   // If the add was a success
	   if (data.UserMessage.IsSuccess) {
		  // Refresh the grid to see the new addition
		  ValuedPartnerSampleARInvoiceEntryCustomizationUI.refreshGrid();
	   }
	   // Show the success message
	   sg.utls.showMessage(data);
	},
	
	// Callback from save click where it was determined that this is
	// an existing record. Thus, it performed a Get and this is the callback from
	// that Get with the record from the database (in case someone else just updated)
	update: function(viewModel) {
	   // Assign to parameters object for Save call
	   var model = viewModel.Data;
	   // Assign values from controls
	   model.DateLastMaintained = new Date();
	   model.Description = $("#vpPaymentCodeDescTextbox").val();
	   model.PaymentType = $('#vpPaymentCodeTypeDropdown').data("kendoDropDownList").value();

	   // Assign url (module, controller, action)
	   var url = sg.utls.url.buildUrl("AR", "PaymentCode", "Save");
	   // Post and set callback
	   sg.utls.ajaxPost(url, model, ValuedPartnerSampleARInvoiceEntryCustomizationUICallback.save);
	},
	
	// Callback from delete
	delete: function (data) {
	   // If delete was a success
	   if (data.UserMessage.IsSuccess) {
		  // Clear controls
		  $("#vpPaymentCodeTextbox").val(""),
		  $("#vpPaymentCodeDescTextbox").val(""),
		  $('#vpModifiedDatePicker').data("kendoDatePicker").value(new Date());
		  $("#vpPaymentCodeTypeDropdown").data("kendoDropDownList").select(0);
		  // Refresh the grid
		  ValuedPartnerSampleARInvoiceEntryCustomizationUI.refreshGrid();
	   }

	   // Show message of delete action
	   sg.utls.showMessage(data);
	}
};

// Initial Entry
$(function () {
    ValuedPartnerSampleARInvoiceEntryCustomizationUI.init();
});
